import { useState } from "react";
import { ArrowRight, Eye, EyeOff, Sparkles } from "lucide-react";
import { Link, useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useAuth } from "@/lib/auth";
import { useToast } from "@/hooks/use-toast";

export default function Login() {
  const [, navigate] = useLocation(); const { login } = useAuth(); const { toast } = useToast(); const [form, setForm] = useState({ email: "", password: "" }); const [showPassword, setShowPassword] = useState(false); const [loading, setLoading] = useState(false);
  const submit = async (event) => { event.preventDefault(); setLoading(true); const result = await login(form.email, form.password); setLoading(false); if (result.success) { toast({ title: "Welcome back", description: "Your learning space is ready." }); navigate("/"); } else toast({ title: "Login failed", description: result.error, variant: "destructive" }); };
  return <div className="auth-page"><div className="auth-glow" /><div className="auth-brand"><Link href="/" className="brand-mark"><span className="brand-symbol"><span /><span /></span><span>Skill<span className="brand-accent">Swap</span></span></Link><Link href="/" className="auth-back">Back to home</Link></div><div className="auth-layout"><div className="auth-pitch"><span className="eyebrow text-cyan-300"><Sparkles /> The exchange starts here</span><h1>Welcome back to your <span>learning network.</span></h1><p>Pick up a conversation, discover a new match, and keep building the skills that matter to you.</p><div className="auth-quote">“Everyone has something worth teaching.”</div></div><div className="auth-card"><div className="auth-card-head"><span className="eyebrow">Your workspace</span><h2>Log in</h2><p>Continue where your curiosity left off.</p></div><form onSubmit={submit} className="auth-form"><div><Label htmlFor="login-email">Email address</Label><Input id="login-email" type="email" autoComplete="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} required /></div><div><Label htmlFor="login-password">Password</Label><div className="password-field"><Input id="login-password" type={showPassword ? "text" : "password"} autoComplete="current-password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} required /><button type="button" aria-label={showPassword ? "Hide password" : "Show password"} onClick={() => setShowPassword((value) => !value)}>{showPassword ? <EyeOff /> : <Eye />}</button></div></div><Button className="button-bright w-full" size="lg" disabled={loading}>{loading ? "Signing in..." : "Log in"} <ArrowRight /></Button></form><p className="auth-switch">New to SkillSwap? <Link href="/signup">Create an account</Link></p></div></div></div>;
}
