import { useQuery } from "@tanstack/react-query";
import { ArrowRight, Check, Sparkles, Star } from "lucide-react";
import { Link } from "wouter";
import { AppShell } from "@/components/AppShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { useAuth } from "@/lib/auth";

export default function Matches() {
  const { user } = useAuth();
  const query = useQuery({ queryKey: ["/api/matches"], queryFn: async () => { const response = await fetch("/api/matches", { credentials: "include" }); if (!response.ok) throw new Error("Unable to load your matches."); return response.json(); } });
  return <AppShell pageLabel="Matches"><div className="shell app-page"><div className="page-heading-row"><div><span className="eyebrow text-cyan-300">Personalized for you</span><h1>Your learning<br /><span className="heading-gradient">matches.</span></h1><p>People whose skills complement what you want to learn.</p></div><Link href="/profile"><Button variant="outline">Tune your profile <ArrowRight /></Button></Link></div>{query.isLoading && <div className="app-card-grid">{[1, 2].map((item) => <div className="dashboard-skeleton match-skeleton" key={item} />)}</div>}{query.isError && <div className="app-empty"><Sparkles /><h2>Something went wrong</h2><p>We couldn't load your learning matches.</p><Button onClick={() => query.refetch()}>Try again</Button></div>}{!query.isLoading && !query.isError && !query.data?.matches?.length && <div className="app-empty"><Sparkles /><h2>No matches yet</h2><p>Complete your profile with skills you teach and want to learn to improve matching.</p><Link href="/profile"><Button>Edit profile <ArrowRight /></Button></Link></div>}<div className="match-card-grid">{query.data?.matches?.map((match) => <Card className="match-card" key={match.user.id}><CardContent className="p-6"><div className="match-card-head"><div className="flex items-center gap-3"><img className="app-card-avatar" src={match.user.avatar || "https://placehold.co/100x100/171a35/9ba7ff?text=SS"} alt={match.user.name} /><div><h2>{match.user.name}</h2><span className="user-meta">{match.user.location || "Location not provided"}</span></div></div><div className="match-score-chip"><strong>{match.compatibilityScore}%</strong><span>match</span></div></div><div className="match-exchange"><div><span className="eyebrow">You want</span><div className="skill-row">{(user.skillsWanted || []).map((skill) => <Badge className="skill-pill skill-pill-green" key={skill}>{skill}</Badge>)}</div></div><ArrowRight className="match-exchange-arrow" /><div><span className="eyebrow">They offer</span><div className="skill-row">{(match.user.skillsOffered || []).map((skill) => <Badge className="skill-pill skill-pill-blue" key={skill}>{skill}</Badge>)}</div></div></div><div className="match-reasons"><span className="eyebrow">Why you match</span>{match.reasons.map((reason) => <p key={reason}><Check /> {reason}</p>)}</div><div className="match-card-footer"><span><Star /> {((match.user.rating || 0) / 10).toFixed(1)} rating</span><Link href={`/profile?user=${match.user.id}`}><Button>View profile <ArrowRight /></Button></Link></div></CardContent></Card>)}</div></div></AppShell>;
}
