import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowRight, Check, Clock3, Inbox, Send, X } from "lucide-react";
import { Link } from "wouter";
import { AppShell } from "@/components/AppShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { useToast } from "@/hooks/use-toast";
import { apiRequest } from "@/lib/queryClient";

function StatusBadge({ status }) { const icon = { pending: Clock3, accepted: Check, rejected: X, cancelled: X }[status] || Clock3; const Icon = icon; return <Badge className={`status-badge status-${status}`}><Icon /> {status}</Badge>; }
export default function Requests() {
  const { toast } = useToast(); const queryClient = useQueryClient(); const query = useQuery({ queryKey: ["/api/swap-requests"], queryFn: async () => { const response = await fetch("/api/swap-requests", { credentials: "include" }); if (!response.ok) throw new Error("Unable to load your requests."); return response.json(); } });
  const mutation = useMutation({ mutationFn: ({ id, status }) => apiRequest("PATCH", `/api/swap-requests/${id}/status`, { status }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["/api/swap-requests"] }); queryClient.invalidateQueries({ queryKey: ["/api/matches"] }); toast({ title: "Request updated" }); }, onError: (error) => toast({ title: "Request update failed", description: error.message, variant: "destructive" }) });
  const requests = query.data?.requests || []; const received = requests.filter((request) => request.toUserId !== undefined); const sent = requests.filter((request) => request.fromUserId !== undefined);
  const RequestCard = ({ request, incoming }) => <Card className="request-card"><CardContent className="p-5"><div className="request-card-head"><div className="request-avatar">{incoming ? <Inbox /> : <Send />}</div><div><span className="eyebrow">{incoming ? "Incoming request" : "Sent request"}</span><h2>Skill exchange #{request.id}</h2></div><StatusBadge status={request.status} /></div><p className="request-message">{request.message || "No message was included with this request."}</p><div className="request-meta"><span>Created {request.createdAt ? new Date(request.createdAt).toLocaleDateString() : "recently"}</span>{request.status === "accepted" && <span className="request-success"><Check /> Learning partners</span>}</div>{request.status === "pending" && <div className="request-actions">{incoming ? <><Button disabled={mutation.isPending} onClick={() => mutation.mutate({ id: request.id, status: "accepted" })}>Accept <Check /></Button><Button variant="outline" disabled={mutation.isPending} onClick={() => mutation.mutate({ id: request.id, status: "rejected" })}>Reject <X /></Button></> : <Button variant="outline" disabled={mutation.isPending} onClick={() => mutation.mutate({ id: request.id, status: "cancelled" })}>Cancel request <X /></Button>}</div>}</CardContent></Card>;
  return <AppShell pageLabel="Requests"><div className="shell app-page"><div className="page-heading-row"><div><span className="eyebrow text-cyan-300">Your activity</span><h1>Swap requests.</h1><p>Keep every learning connection moving in the right direction.</p></div><Link href="/browse"><Button>Find people <ArrowRight /></Button></Link></div>{query.isLoading && <div className="app-card-grid">{[1, 2].map((item) => <div className="dashboard-skeleton request-skeleton" key={item} />)}</div>}{query.isError && <div className="app-empty"><Inbox /><h2>Something went wrong</h2><p>We couldn't load your requests.</p><Button onClick={() => query.refetch()}>Try again</Button></div>}<div className="request-columns"><section><div className="section-label"><Inbox /><div><h2>Received</h2><span>People reaching out to you</span></div></div>{received.length ? received.map((request) => <RequestCard key={`received-${request.id}`} request={request} incoming />) : <div className="mini-empty">No incoming requests yet.</div>}</section><section><div className="section-label"><Send /><div><h2>Sent</h2><span>Your open conversations</span></div></div>{sent.length ? sent.map((request) => <RequestCard key={`sent-${request.id}`} request={request} />) : <div className="mini-empty">You have not sent a request yet.</div>}</section></div></div></AppShell>;
}
