import { Link } from "wouter";
import { Bell, LockKeyhole, ShieldCheck, UserRound } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useAuth } from "@/lib/auth";

export default function Settings() {
  const { user } = useAuth();
  return <AppShell pageLabel="Settings"><div className="shell app-page narrow-page"><div className="page-heading"><span className="eyebrow text-cyan-300">Your account</span><h1>Account settings</h1><p>Keep your identity, privacy, and learning preferences up to date.</p></div><div className="settings-stack"><Card className="settings-card"><CardHeader><CardTitle><UserRound /> Account</CardTitle></CardHeader><CardContent><div className="settings-row"><div><span className="settings-label">Name</span><strong>{user.name}</strong></div><Link href="/profile"><Button variant="outline">Edit profile</Button></Link></div><div className="settings-row"><div><span className="settings-label">Email</span><strong>{user.email}</strong></div><span className="settings-note">Managed from your profile</span></div><div className="settings-row"><div><span className="settings-label">Username</span><strong>@{user.username}</strong></div></div></CardContent></Card><Card className="settings-card"><CardHeader><CardTitle><ShieldCheck /> Privacy & discovery</CardTitle></CardHeader><CardContent><div className="settings-row"><div><span className="settings-label">Profile visibility</span><strong>{user.isPublic ? "Public profile" : "Private profile"}</strong><p>Your public profile can appear in Browse and matching.</p></div><Link href="/profile"><Button variant="outline">Manage</Button></Link></div><div className="settings-row"><div><span className="settings-label">Availability</span><strong>{(user.availability || []).join(", ") || "Not set"}</strong></div></div></CardContent></Card><Card className="settings-card"><CardHeader><CardTitle><LockKeyhole /> Security</CardTitle></CardHeader><CardContent><div className="settings-row"><div><span className="settings-label">Password</span><strong>Your password is securely hashed</strong><p>Password changes are not enabled in the current API.</p></div></div></CardContent></Card><Card className="settings-card"><CardHeader><CardTitle><Bell /> Updates</CardTitle></CardHeader><CardContent><div className="settings-row"><div><span className="settings-label">Notifications</span><strong>No notification service connected yet</strong><p>Request updates will appear here when notifications are available.</p></div><Link href="/notifications"><Button variant="outline">View notifications</Button></Link></div></CardContent></Card></div></div></AppShell>;
}
